malina141_sylius_wishlist_shop_index:
    path: /{_locale}/wishlist
    methods: [GET]
    controller: malina141_sylius_wishlist.controller.wishlist_item::indexAction
    defaults:
        _sylius:
            section: shop_account
            template: '@Malina141SyliusWishlistPlugin/shop/account/wishlist/index.html.twig'
            grid: sylius_shop_wishlist

malina141_sylius_wishlist_shop_item_delete:
    path: /{_locale}/wishlist/item/{id}
    methods: [DELETE]
    controller: malina141_sylius_wishlist.controller.wishlist_item::deleteAction
    defaults:
        _sylius:
            repository:
                method: findOneByIdAndWishlist
                arguments:
                    - $id
                    - expr:service('malina141_sylius_wishlist.context.wishlist').getWishlist()
            redirect:
                route: malina141_sylius_wishlist_shop_index

malina141_sylius_wishlist_shop_item_bulk_delete:
    path: /{_locale}/wishlist/item-bulk-delete
    methods: [DELETE]
    controller: malina141_sylius_wishlist.controller.wishlist_item::bulkDeleteAction
    defaults:
        _sylius:
            repository:
                method: findByIdsAndWishlist
                arguments:
                    - $ids
                    - expr:service('malina141_sylius_wishlist.context.wishlist').getWishlist()
            redirect:
                route: malina141_sylius_wishlist_shop_index

malina141_sylius_wishlist_shop_item_bulk_add_to_cart:
    path: /{_locale}/wishlist/item-add-to-cart
    methods: [POST]
    controller: malina141_sylius_wishlist.controller.action.add_wishlist_items_to_cart

malina141_sylius_wishlist_shop_share:
    path: /{_locale}/wishlist/share
    methods: [POST]
    controller: malina141_sylius_wishlist.controller.wishlist::applyStateMachineTransitionAction
    defaults:
        _sylius:
            repository:
                method: find
                arguments:
                    - expr:service('malina141_sylius_wishlist.context.wishlist').getWishlist().getId()
            state_machine:
                graph: malina141_sylius_wishlist
                transition: share
            redirect:
                route: malina141_sylius_wishlist_shop_index

malina141_sylius_wishlist_shop_unshare:
    path: /{_locale}/wishlist/unshare
    methods: [POST]
    controller: malina141_sylius_wishlist.controller.wishlist::applyStateMachineTransitionAction
    defaults:
        _sylius:
            repository:
                method: find
                arguments:
                    - expr:service('malina141_sylius_wishlist.context.wishlist').getWishlist().getId()
            state_machine:
                graph: malina141_sylius_wishlist
                transition: unshare
            redirect:
                route: malina141_sylius_wishlist_shop_index

malina141_sylius_wishlist_shop_share_show:
    path: /{_locale}/wishlist/share/{token}
    methods: [GET]
    controller: malina141_sylius_wishlist.controller.wishlist::showAction
    defaults:
        _sylius:
            permission: false
            repository:
                method: findOneByShareTokenAndChannel
                arguments:
                    - $token
                    - expr:service('sylius.context.channel').getChannel()
            template: '@Malina141SyliusWishlistPlugin/shop/account/wishlist/share/show.html.twig'
