sylius_grid:
    templates:
        action:
            shop_share: '@Malina141SyliusWishlistPlugin/shop/account/wishlist/grid/action/share.html.twig'
        bulk_action:
            malina141_bulk_delete: '@Malina141SyliusWishlistPlugin/shop/account/wishlist/grid/bulk_action/malina141_bulk_delete.html.twig'
            shop_bulk_add_to_cart: '@Malina141SyliusWishlistPlugin/shop/account/wishlist/grid/bulk_action/shop_bulk_add_to_cart.html.twig'
    grids:
        sylius_shop_wishlist:
            driver:
                name: doctrine/orm
                options:
                    class: "%malina141_sylius_wishlist.model.wishlist_item.class%"
                    repository:
                        method: createShopWishlistItemQueryBuilder
                        arguments:
                            wishlist: expr:service('malina141_sylius_wishlist.context.wishlist').getWishlist()
            fields:
                productVariant.product.name:
                    type: twig
                    path: .
                    label: sylius.ui.product
                    options:
                        template: '@Malina141SyliusWishlistPlugin/shop/account/wishlist/grid/field/product_name.html.twig'
                productVariant.optionValues:
                    type: twig
                    path: .
                    label: sylius.ui.options
                    options:
                        template: '@Malina141SyliusWishlistPlugin/shop/account/wishlist/grid/field/options.html.twig'
                price:
                    type: twig
                    path: .
                    label: sylius.ui.price
                    options:
                        template: '@Malina141SyliusWishlistPlugin/shop/account/wishlist/grid/field/price.html.twig'
            actions:
                main:
                    share:
                        type: shop_share
                        label: malina141_sylius_wishlist.ui.share
                        options:
                            link:
                                route: malina141_sylius_wishlist_shop_share
                            wishlist: expr:service('malina141_sylius_wishlist.context.wishlist').getWishlist()
                item:
                    delete:
                        type: shop_delete
                        options:
                            link:
                                route: malina141_sylius_wishlist_shop_item_delete
                bulk:
                    malina141_bulk_delete:
                        type: malina141_bulk_delete
                        label: sylius.ui.delete
                        options:
                            link:
                                route: malina141_sylius_wishlist_shop_item_bulk_delete
                    shop_bulk_add_to_cart:
                        type: shop_bulk_add_to_cart
                        label: sylius.ui.add_to_cart
                        options:
                            link:
                                route: malina141_sylius_wishlist_shop_item_bulk_add_to_cart
